# Site Settings
title: "Consulting Co"
subtitle: "Placeholder Tagline Here"
name: "Consulting Co"
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Professional consulting services."
url: ""
baseurl: ""
repository: ""

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Site Author
author:
  name: "BoringOps.Run"
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  location: "Lorem City, AB"
  email: "hello@boringops.run"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:hello@boringops.run"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/"

# Reading Files
include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - LICENSE
  - node_modules
  - hero-prototype
  - jekyll-hero

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-archives

# Pagination
paginate: 10
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  services:
    output: true
    permalink: /services/:slug/
  proof:
    output: true
    permalink: /proof/:slug/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: false
      permalink: /articles/:slug/
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _services
  - scope:
      path: ""
      type: services
    values:
      layout: single
      author_profile: false
      share: false
      related: false
  # _proof
  - scope:
      path: ""
      type: proof
    values:
      layout: proof
      author_profile: false
      share: false
      related: false

# Outputting
timezone: America/New_York

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
